trigger: none

schedules:
- cron: '0 0 * * *'
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: false

variables:
  artifactName: enigmatry-entry-code-generation
  projectNamePrefix: Enigmatry.Entry.CodeGeneration
  
resources:
  repositories:
    - repository: templates
      type: git
      name: Enigmatry - Azure Pipelines Templates/enigmatry-azure-pipelines-templates

jobs:
- job: set_dotnet_version
  displayName: Set .Net version
  steps: 
  - task: UseDotNet@2
    displayName: Set .Net version
    inputs:
      version: 9.0.101
- template: code-analysis.yml@templates
  parameters:
    projectName: 'Enigmatry - Entry Code Generation'
    sonarProjectKey: 'AspNetCoreAngular_EnigmatryBlueprintCodeGeneration'
    displayName: 'Code Analysis'

- template: build-report-job.yml@templates
  parameters:
    artifactName: $(artifactName)
    displayName: 'Generate Reports'
    projectNameAngularApp: ''
    projectNamePrefix: $(projectNamePrefix)